### ISSUE TITLE
couch-js-devel

### ISSUE THREAD

**Issue by rolfn** [adrienverge/copr-couchdb#3]
The line
```
BuildRequires: js-devel
```
in `couchdb.spec` should be better
```
BuildRequires: couch-js-devel
```
in the case of inconsistency between the provided files. (not a big problem)

**Comment by adrienverge** [comment]
Agreed, but building the package with mock becomes complicated because `couch-js-devel` is not available from main repos.

Any solution? For example a series of commands to get `mock -r epel-7-x86_64 rebuild ~/rpmbuild/SRPMS/couchdb-2.1.2-*.src.rpm` working with `BuildRequires: couch-js-devel`?

**Comment by rolfn** [comment]
Sorry, I don't know anything about `mock`. I adapted your code for openSUSE (see [my repository](/rolfn/couchdb2-opensuse)) and here we use `rpmbuild`, which knows if `couch-js-devel` is installed. 

By the way: CouchDB 2.2.0 is out. See http://apache.mirror.digionline.de/couchdb/source/
